###############################################################
#### Example 01: Depth-dependent tectonic stress states
#### classified using the combined NGC + Ucar failure criterion
####
#### Purpose:
####   - Read the combined NGC–UC curve generated by script 01
####   - Calculate effective stress states with depth
####   - Include pore-fluid pressure, lithostatic stress,
####     Biot coefficient and tectonic stress
####   - Classify stress states as:
####       1) No failure
####       2) Pure extensional fracture
####       3) Transitional / hybrid shear fracture
####   - Refine transition depths to metre-scale resolution
####   - Export tables with stress states, transition depths,
####     fracture intervals and critical Mohr circles
####
#### Required input files:
####   results/tables/curve_combined_NGC_UC.csv
####   results/tables/parameters_NGC_UC.csv
####
#### Outputs:
####   - CSV tables in results/tables/
####
#### Suggested file name:
####   03_example_01_depth_stress_fracture_domains.R
###############################################################

# ============================================================
# 1. Install and load libraries
# ============================================================

paquetes <- c("dplyr", "readr", "tidyr")

instalar_faltantes <- paquetes[
  !sapply(paquetes, requireNamespace, quietly = TRUE)
]

if (length(instalar_faltantes) > 0) {
  install.packages(instalar_faltantes)
}

lapply(paquetes, library, character.only = TRUE)


# ============================================================
# 2. Input files from script 01
# ============================================================

curve_file <- "results/tables/curve_combined_NGC_UC.csv"
param_file <- "results/tables/parameters_NGC_UC.csv"

if (!file.exists(curve_file)) {
  stop("Curve file not found: ", curve_file)
}

if (!file.exists(param_file)) {
  stop("Parameter file not found: ", param_file)
}

curve_combined <- read_csv(curve_file, show_col_types = FALSE)
parameters_ngc_uc <- read_csv(param_file, show_col_types = FALSE)


# ============================================================
# 3. User-defined physical parameters
# ============================================================

gamma_r <- 24       # kN/m^3; mean unit weight of rock
gamma_w <- 9.81     # kN/m^3; unit weight of water

alpha_biot <- 1.0   # Biot coefficient
nu <- 0.22          # Poisson's ratio

# Tectonic stress values, MPa
# Negative values correspond to extensional regimes
TS_values <- seq(-20, 0, by = 5)

# Coarse depth domain, m
depths <- seq(0, 5000, by = 25)

# Water table depth, m
# z_water = 0 means water table at surface
z_water <- 0


# ============================================================
# 4. Refinement and truncation settings
# ============================================================

use_transition_refinement <- TRUE
refinement_half_window_m <- 50
refinement_step_m <- 1

truncate_after_no_failure <- TRUE


# ============================================================
# 5. Output folders
# ============================================================

dir.create("results", showWarnings = FALSE)
dir.create("results/tables", recursive = TRUE, showWarnings = FALSE)


# ============================================================
# 6. Basic checks
# ============================================================

stopifnot(gamma_r > 0)
stopifnot(gamma_w > 0)
stopifnot(alpha_biot >= 0)
stopifnot(nu > 0, nu < 0.5)
stopifnot(all(depths >= 0))
stopifnot(refinement_step_m > 0)
stopifnot(refinement_half_window_m >= 0)


# ============================================================
# 7. Extract NGC–UC parameters
# ============================================================

T0 <- parameters_ngc_uc$sigma_t_adj[1]
C0 <- parameters_ngc_uc$sigma_c_adj[1]
lambda <- parameters_ngc_uc$lambda[1]

if (!is.finite(T0) || !is.finite(C0) || !is.finite(lambda)) {
  stop("Could not extract T0, C0 or lambda from parameters file.")
}

pure_extensional_sigma1_limit <- -lambda * T0


# ============================================================
# 8. Prepare failure-threshold interpolation
# ============================================================

curve_threshold <- curve_combined %>%
  filter(
    is.finite(sigma_1),
    is.finite(sigma_3),
    sigma_1 >= 0
  ) %>%
  arrange(sigma_1) %>%
  group_by(sigma_1) %>%
  summarise(
    sigma_3_threshold = min(sigma_3, na.rm = TRUE),
    .groups = "drop"
  )

if (nrow(curve_threshold) < 2) {
  stop(
    "Not enough points in the NGC–UC curve to interpolate failure thresholds. ",
    "Check that results/tables/curve_combined_NGC_UC.csv contains enough ",
    "sigma_1 and sigma_3 values. Consider increasing n_ngc and n_uc in script 01."
  )
}

sigma_1_curve_max <- max(curve_threshold$sigma_1, na.rm = TRUE)

if (sigma_1_curve_max < C0) {
  warning(
    "The available NGC–UC curve does not reach C0 in sigma_1. ",
    "The hybrid/shear classification will be limited to the available curve range: ",
    round(sigma_1_curve_max, 3), " MPa. ",
    "Consider increasing n_ngc and n_uc in script 01."
  )
}

interp_sigma3_threshold <- approxfun(
  x = curve_threshold$sigma_1,
  y = curve_threshold$sigma_3_threshold,
  rule = 2
)


# ============================================================
# 9. Function to calculate and classify stress states
# ============================================================

classify_stress_states <- function(df) {
  
  df %>%
    mutate(
      Pf = ifelse(
        depth >= z_water,
        gamma_w * (depth - z_water) / 1000,
        0
      ),
      sigma_v = gamma_r * depth / 1000,
      sigma_1_eff = sigma_v - alpha_biot * Pf,
      sigma_3_eff = (nu / (1 - nu)) * sigma_1_eff + TS,
      
      sigma_3_threshold = interp_sigma3_threshold(sigma_1_eff),
      
      pure_extensional_fracture =
        sigma_3_eff <= T0 &
        sigma_1_eff <= pure_extensional_sigma1_limit,
      
      hybrid_shear_fracture =
        !pure_extensional_fracture &
        sigma_1_eff <= min(C0, sigma_1_curve_max) &
        sigma_3_eff <= sigma_3_threshold,
      
      fracture_type = case_when(
        pure_extensional_fracture ~ "Pure extensional fracture",
        hybrid_shear_fracture ~ "Transitional / hybrid shear fracture",
        TRUE ~ "No failure"
      )
    )
}


# ============================================================
# 10. Coarse depth–tectonic stress model
# ============================================================

stress_model_coarse <- expand.grid(
  depth = depths,
  TS = TS_values
) %>%
  as_tibble() %>%
  classify_stress_states()


# ============================================================
# 11. Detect coarse fracture-type transitions
# ============================================================

transition_candidates <- stress_model_coarse %>%
  arrange(TS, depth) %>%
  group_by(TS) %>%
  mutate(
    previous_fracture_type = lag(fracture_type),
    transition_detected =
      !is.na(previous_fracture_type) &
      fracture_type != previous_fracture_type
  ) %>%
  filter(transition_detected) %>%
  transmute(
    TS = TS,
    depth_transition_coarse = depth,
    previous_fracture_type = previous_fracture_type,
    new_fracture_type = fracture_type
  ) %>%
  ungroup()


# ============================================================
# 12. Local refinement around transitions
# ============================================================

if (use_transition_refinement && nrow(transition_candidates) > 0) {
  
  refined_depths <- transition_candidates %>%
    rowwise() %>%
    mutate(
      depth_seq = list(seq(
        max(0, depth_transition_coarse - refinement_half_window_m),
        depth_transition_coarse + refinement_half_window_m,
        by = refinement_step_m
      ))
    ) %>%
    select(TS, depth_seq) %>%
    unnest(depth_seq) %>%
    rename(depth = depth_seq) %>%
    distinct(TS, depth)
  
  stress_model_refined <- classify_stress_states(refined_depths)
  
  stress_model <- bind_rows(
    stress_model_coarse,
    stress_model_refined
  ) %>%
    distinct(TS, depth, .keep_all = TRUE) %>%
    arrange(TS, depth)
  
} else {
  
  stress_model <- stress_model_coarse
}


# ============================================================
# 13. Optionally truncate after return to "No failure"
# ============================================================

if (truncate_after_no_failure) {
  
  stress_model <- stress_model %>%
    arrange(TS, depth) %>%
    group_by(TS) %>%
    mutate(
      fracture_detected_before =
        cumsum(fracture_type != "No failure") > 0,
      
      no_failure_after_fracture =
        fracture_detected_before &
        fracture_type == "No failure",
      
      keep_row =
        cumsum(no_failure_after_fracture) <= 1
    ) %>%
    filter(keep_row) %>%
    select(
      -fracture_detected_before,
      -no_failure_after_fracture,
      -keep_row
    ) %>%
    ungroup()
}


# ============================================================
# 14. Critical transition depths after refinement
# ============================================================

critical_depths <- stress_model %>%
  arrange(TS, depth) %>%
  group_by(TS) %>%
  mutate(
    previous_fracture_type = lag(fracture_type),
    transition_detected =
      !is.na(previous_fracture_type) &
      fracture_type != previous_fracture_type
  ) %>%
  filter(transition_detected) %>%
  transmute(
    TS = TS,
    depth_m = depth,
    from = previous_fracture_type,
    to = fracture_type,
    sigma_1_eff = sigma_1_eff,
    sigma_3_eff = sigma_3_eff,
    Pf = Pf,
    sigma_v = sigma_v,
    sigma_3_threshold = sigma_3_threshold
  ) %>%
  ungroup()


# ============================================================
# 15. Summaries by tectonic stress
# ============================================================

fracture_intervals_by_TS <- stress_model %>%
  filter(fracture_type != "No failure") %>%
  group_by(TS, fracture_type) %>%
  summarise(
    depth_min = min(depth, na.rm = TRUE),
    depth_max = max(depth, na.rm = TRUE),
    sigma_1_min = min(sigma_1_eff, na.rm = TRUE),
    sigma_1_max = max(sigma_1_eff, na.rm = TRUE),
    sigma_3_min = min(sigma_3_eff, na.rm = TRUE),
    sigma_3_max = max(sigma_3_eff, na.rm = TRUE),
    n_cases = n(),
    .groups = "drop"
  )


# ============================================================
# 16. Mohr circles for critical depths
# ============================================================

make_mohr_circles <- function(df, n = 361) {
  
  theta <- seq(0, 2 * pi, length.out = n)
  
  do.call(
    rbind,
    lapply(seq_len(nrow(df)), function(i) {
      
      s1  <- df$sigma_1[i]
      s3  <- df$sigma_3[i]
      cen <- 0.5 * (s1 + s3)
      rad <- 0.5 * (s1 - s3)
      
      data.frame(
        id = df$id[i],
        sigma = cen + rad * cos(theta),
        tau = rad * sin(theta)
      )
    })
  )
}

if (nrow(critical_depths) > 0) {
  
  critical_mohr_input <- critical_depths %>%
    mutate(
      id = row_number(),
      sigma_1 = sigma_1_eff,
      sigma_3 = sigma_3_eff,
      label = paste0("TS=", TS, ", z=", round(depth_m), " m")
    )
  
  critical_mohr <- make_mohr_circles(
    critical_mohr_input %>%
      select(id, sigma_1, sigma_3),
    n = 361
  ) %>%
    left_join(
      critical_mohr_input %>% select(id, label, to),
      by = "id"
    )
  
} else {
  
  critical_mohr_input <- tibble()
  critical_mohr <- tibble()
}


# ============================================================
# 17. Export CSV files
# ============================================================

write_csv(
  stress_model,
  "results/tables/example_01_depth_stress_fracture_classification.csv"
)

write_csv(
  stress_model_coarse,
  "results/tables/example_01_depth_stress_fracture_classification_coarse.csv"
)

write_csv(
  transition_candidates,
  "results/tables/example_01_transition_candidates_coarse.csv"
)

write_csv(
  critical_depths,
  "results/tables/example_01_critical_transition_depths.csv"
)

write_csv(
  fracture_intervals_by_TS,
  "results/tables/example_01_fracture_intervals_by_TS.csv"
)

write_csv(
  curve_threshold,
  "results/tables/example_01_sigma3_failure_threshold_from_curve.csv"
)

if (nrow(critical_mohr) > 0) {
  
  write_csv(
    critical_mohr,
    "results/tables/example_01_critical_mohr_circles.csv"
  )
  
  write_csv(
    critical_mohr_input,
    "results/tables/example_01_critical_mohr_input.csv"
  )
}

example_parameters <- data.frame(
  gamma_r = gamma_r,
  gamma_w = gamma_w,
  alpha_biot = alpha_biot,
  nu = nu,
  z_water = z_water,
  depth_min = min(depths),
  depth_max = max(depths),
  depth_step_coarse = unique(diff(depths))[1],
  use_transition_refinement = use_transition_refinement,
  refinement_half_window_m = refinement_half_window_m,
  refinement_step_m = refinement_step_m,
  truncate_after_no_failure = truncate_after_no_failure,
  TS_values = paste(TS_values, collapse = ", "),
  T0 = T0,
  C0 = C0,
  sigma_1_curve_max = sigma_1_curve_max,
  lambda = lambda,
  pure_extensional_sigma1_limit = pure_extensional_sigma1_limit
)

write_csv(
  example_parameters,
  "results/tables/example_01_parameters.csv"
)


# ============================================================
# 18. Console checks
# ============================================================

cat("\n==============================================\n")
cat("Example 01: Depth-dependent fracture domains\n")
cat("==============================================\n")
cat("Input curve file :", curve_file, "\n")
cat("Input param file :", param_file, "\n\n")

cat("Physical parameters:\n")
cat("gamma_r    =", gamma_r, "kN/m^3\n")
cat("gamma_w    =", gamma_w, "kN/m^3\n")
cat("alpha_biot =", alpha_biot, "\n")
cat("nu         =", nu, "\n")
cat("z_water    =", z_water, "m\n")
cat("TS values  =", paste(TS_values, collapse = ", "), "MPa\n\n")

cat("NGC–UC thresholds:\n")
cat("T0 =", T0, "MPa\n")
cat("C0 =", C0, "MPa\n")
cat("sigma_1_curve_max =", sigma_1_curve_max, "MPa\n")
cat("lambda =", lambda, "\n")
cat("Pure extensional sigma_1 limit =", pure_extensional_sigma1_limit, "MPa\n\n")

cat("Refinement:\n")
cat("use_transition_refinement =", use_transition_refinement, "\n")
cat("refinement_half_window_m  =", refinement_half_window_m, "m\n")
cat("refinement_step_m         =", refinement_step_m, "m\n")
cat("truncate_after_no_failure =", truncate_after_no_failure, "\n\n")

cat("Rows exported:\n")
cat("Coarse stress model rows :", nrow(stress_model_coarse), "\n")
cat("Final stress model rows  :", nrow(stress_model), "\n")
cat("Critical transitions     :", nrow(critical_depths), "\n")
cat("Fracture intervals       :", nrow(fracture_intervals_by_TS), "\n")
cat("Critical Mohr rows       :", nrow(critical_mohr), "\n\n")

cat("Fracture types detected:\n")
print(table(stress_model$fracture_type))

cat("\nFiles written to:\n")
cat("results/tables/\n")
cat("==============================================\n")