###############################################################
#### Example 02: Cooling-induced failure in a geothermal reservoir
#### using the combined NGC + Ucar failure criterion
####
#### Purpose:
####   - Read the combined NGC–UC curve generated by script 01
####   - Simulate thermal cooling at a given depth
####   - Calculate the evolution of effective principal stresses
####   - Identify the cooling required to reach failure
####   - Stop the plotted cooling path at first failure
####   - Export tables and plots
####
#### Required input files:
####   results/tables/curve_combined_NGC_UC.csv
####   results/tables/parameters_NGC_UC.csv
####
#### Outputs:
####   - CSV tables in results/tables/
####   - PNG/PDF figures in results/figures/
###############################################################

# ============================================================
# 1. Install and load libraries
# ============================================================

paquetes <- c("ggplot2", "dplyr", "readr")

instalar_faltantes <- paquetes[
  !sapply(paquetes, requireNamespace, quietly = TRUE)
]

if (length(instalar_faltantes) > 0) {
  install.packages(instalar_faltantes)
}

lapply(paquetes, library, character.only = TRUE)


# ============================================================
# 2. Input files from script 01
# ============================================================

curve_file <- "results/tables/curve_combined_NGC_UC.csv"
param_file <- "results/tables/parameters_NGC_UC.csv"

if (!file.exists(curve_file)) {
  stop("Curve file not found: ", curve_file)
}

if (!file.exists(param_file)) {
  stop("Parameter file not found: ", param_file)
}

curve_combined <- read_csv(curve_file, show_col_types = FALSE)
parameters_ngc_uc <- read_csv(param_file, show_col_types = FALSE)


# ============================================================
# 3. User-defined physical parameters
# ============================================================

z <- 5000                 # depth, m
gamma_eff <- 17           # effective unit weight, kN/m^3

nu <- 0.09                # Poisson's ratio
alpha_T <- 2e-5           # thermal expansion coefficient, 1/K
E <- 91e3                 # Young's modulus, MPa

T_ini <- 450              # initial temperature, K

# Cooling range
delta_T_seq <- seq(0, 60, by = 0.1)


# ============================================================
# 3.1. User-defined plot limits
# ============================================================

use_default_plot_limits <- TRUE
plot_margin <- 0.10

# Manual limits used only if use_default_plot_limits <- FALSE
manual_xlim_sigma3_sigma1 <- c(-40, 120)
manual_ylim_sigma3_sigma1 <- c(0, 180)

manual_xlim_sigma_tau <- c(-40, 120)
manual_ylim_sigma_tau <- c(0, 120)


# ============================================================
# 4. Output folders
# ============================================================

dir.create("results", showWarnings = FALSE)
dir.create("results/tables", recursive = TRUE, showWarnings = FALSE)
dir.create("results/figures", recursive = TRUE, showWarnings = FALSE)


# ============================================================
# 5. Basic checks
# ============================================================

stopifnot(z > 0)
stopifnot(gamma_eff > 0)
stopifnot(nu > 0, nu < 0.5)
stopifnot(alpha_T > 0)
stopifnot(E > 0)
stopifnot(all(delta_T_seq >= 0))


# ============================================================
# 6. Extract NGC–UC parameters
# ============================================================

T0 <- parameters_ngc_uc$sigma_t_adj[1]
C0 <- parameters_ngc_uc$sigma_c_adj[1]
lambda <- parameters_ngc_uc$lambda[1]

if (!is.finite(T0) || !is.finite(C0) || !is.finite(lambda)) {
  stop("Could not extract T0, C0 or lambda from parameters file.")
}

pure_extensional_sigma1_limit <- -lambda * T0


# ============================================================
# 7. Prepare failure-threshold interpolation
# ============================================================

curve_threshold <- curve_combined %>%
  filter(
    is.finite(sigma_1),
    is.finite(sigma_3),
    sigma_1 >= 0
  ) %>%
  arrange(sigma_1) %>%
  group_by(sigma_1) %>%
  summarise(
    sigma_3_threshold = min(sigma_3, na.rm = TRUE),
    .groups = "drop"
  )

if (nrow(curve_threshold) < 2) {
  stop(
    "Not enough points in the NGC–UC curve to interpolate failure thresholds. ",
    "Consider increasing n_ngc and n_uc in script 01."
  )
}

sigma_1_curve_max <- max(curve_threshold$sigma_1, na.rm = TRUE)

if (sigma_1_curve_max < C0) {
  warning(
    "The available NGC–UC curve does not reach C0 in sigma_1. ",
    "The failure check will be limited to the available curve range: ",
    round(sigma_1_curve_max, 3), " MPa."
  )
}

interp_sigma3_threshold <- approxfun(
  x = curve_threshold$sigma_1,
  y = curve_threshold$sigma_3_threshold,
  rule = 2
)


# ============================================================
# 8. Cooling simulation
# ============================================================

k0 <- nu / (1 - nu)

sigma_v_ini <- gamma_eff * z / 1000  # MPa

cooling_results <- data.frame(delta_T = delta_T_seq) %>%
  mutate(
    T_current = T_ini - delta_T,
    
    delta_sigma_thermal =
      (alpha_T * E / (1 - nu)) * delta_T,
    
    sigma_v = sigma_v_ini,
    sigma_h = k0 * sigma_v - delta_sigma_thermal,
    
    sigma_1 = pmax(sigma_v, sigma_h),
    sigma_3 = pmin(sigma_v, sigma_h),
    
    sigma_3_threshold = interp_sigma3_threshold(sigma_1),
    
    pure_extensional_failure =
      sigma_3 <= T0 &
      sigma_1 <= pure_extensional_sigma1_limit,
    
    hybrid_shear_failure =
      !pure_extensional_failure &
      sigma_1 <= min(C0, sigma_1_curve_max) &
      sigma_3 <= sigma_3_threshold,
    
    failure_type = case_when(
      pure_extensional_failure ~ "Pure extensional fracture",
      hybrid_shear_failure ~ "Transitional / hybrid shear fracture",
      TRUE ~ "No failure"
    ),
    
    failure = failure_type != "No failure"
  )

first_failure_point <- cooling_results %>%
  filter(failure) %>%
  slice(1)

if (nrow(first_failure_point) == 0) {
  first_failure_point <- data.frame()
}

# Keep only the cooling path up to the first failure point
if (nrow(first_failure_point) == 1) {
  
  first_failure_delta_T <- first_failure_point$delta_T[1]
  
  cooling_results_plot <- cooling_results %>%
    filter(delta_T <= first_failure_delta_T)
  
} else {
  
  first_failure_delta_T <- NA_real_
  cooling_results_plot <- cooling_results
}


# ============================================================
# 9. Mohr circles for simulated cooling path
# ============================================================

make_mohr_circles <- function(df, n = 181) {
  
  theta <- seq(0, pi, length.out = n)
  
  do.call(
    rbind,
    lapply(seq_len(nrow(df)), function(i) {
      
      s1 <- df$sigma_1[i]
      s3 <- df$sigma_3[i]
      cen <- (s1 + s3) / 2
      rad <- (s1 - s3) / 2
      
      data.frame(
        delta_T = df$delta_T[i],
        sigma_n = cen + rad * cos(theta),
        tau = rad * sin(theta)
      )
    })
  )
}

# To avoid excessively large files, export only every Nth Mohr circle
mohr_export_step <- 10

mohr_input <- cooling_results_plot %>%
  slice(seq(1, n(), by = mohr_export_step))

# Always include the first failure circle, if present
if (nrow(first_failure_point) == 1) {
  mohr_input <- bind_rows(
    mohr_input,
    first_failure_point
  ) %>%
    distinct(delta_T, .keep_all = TRUE) %>%
    arrange(delta_T)
}

mohr_circles <- make_mohr_circles(mohr_input, n = 181)


# ============================================================
# 10. Plot limits
# ============================================================

if (use_default_plot_limits) {
  
  # sigma_3 - sigma_1 space:
  # limits depend on the failure criterion and on the cooling path
  xlim_sigma3_sigma1 <- c(
    min(c(1.2 * T0, cooling_results_plot$sigma_3), na.rm = TRUE),
    max(c(0.75 * C0, cooling_results_plot$sigma_3, 0), na.rm = TRUE)
  )
  
  ylim_sigma3_sigma1 <- c(
    0,
    max(c(1.10 * C0, cooling_results_plot$sigma_1), na.rm = TRUE)
  )
  
  # sigma_n - tau space:
  # limits depend on T0, C0, Mohr circles and the envelope
  xlim_sigma_tau <- c(
    min(c(1.2 * T0, mohr_circles$sigma_n), na.rm = TRUE),
    max(c(0.75 * C0, mohr_circles$sigma_n), na.rm = TRUE)
  )
  
  ylim_sigma_tau <- c(
    0,
    max(c(0.75 * C0, mohr_circles$tau), na.rm = TRUE)
  )
  
  # Add margin
  xlim_sigma3_sigma1 <- xlim_sigma3_sigma1 +
    c(-1, 1) * plot_margin * diff(xlim_sigma3_sigma1)
  
  ylim_sigma3_sigma1 <- ylim_sigma3_sigma1 +
    c(0, 1) * plot_margin * diff(ylim_sigma3_sigma1)
  
  xlim_sigma_tau <- xlim_sigma_tau +
    c(-1, 1) * plot_margin * diff(xlim_sigma_tau)
  
  ylim_sigma_tau <- ylim_sigma_tau +
    c(0, 1) * plot_margin * diff(ylim_sigma_tau)
  
} else {
  
  xlim_sigma3_sigma1 <- manual_xlim_sigma3_sigma1
  ylim_sigma3_sigma1 <- manual_ylim_sigma3_sigma1
  
  xlim_sigma_tau <- manual_xlim_sigma_tau
  ylim_sigma_tau <- manual_ylim_sigma_tau
}


# ============================================================
# 11. Export CSV tables
# ============================================================

write_csv(
  cooling_results,
  "results/tables/example_02_cooling_simulation_full.csv"
)

write_csv(
  cooling_results_plot,
  "results/tables/example_02_cooling_simulation_until_failure.csv"
)

write_csv(
  first_failure_point,
  "results/tables/example_02_first_failure_point.csv"
)

write_csv(
  curve_threshold,
  "results/tables/example_02_sigma3_failure_threshold_from_curve.csv"
)

write_csv(
  mohr_circles,
  "results/tables/example_02_mohr_circles_until_failure.csv"
)

example_parameters <- data.frame(
  z = z,
  gamma_eff = gamma_eff,
  nu = nu,
  k0 = k0,
  alpha_T = alpha_T,
  E = E,
  T_ini = T_ini,
  delta_T_min = min(delta_T_seq),
  delta_T_max = max(delta_T_seq),
  delta_T_step = unique(diff(delta_T_seq))[1],
  sigma_v_ini = sigma_v_ini,
  T0 = T0,
  C0 = C0,
  sigma_1_curve_max = sigma_1_curve_max,
  lambda = lambda,
  pure_extensional_sigma1_limit = pure_extensional_sigma1_limit,
  mohr_export_step = mohr_export_step,
  use_default_plot_limits = use_default_plot_limits,
  xlim_sigma3_sigma1_min = xlim_sigma3_sigma1[1],
  xlim_sigma3_sigma1_max = xlim_sigma3_sigma1[2],
  ylim_sigma3_sigma1_min = ylim_sigma3_sigma1[1],
  ylim_sigma3_sigma1_max = ylim_sigma3_sigma1[2],
  xlim_sigma_tau_min = xlim_sigma_tau[1],
  xlim_sigma_tau_max = xlim_sigma_tau[2],
  ylim_sigma_tau_min = ylim_sigma_tau[1],
  ylim_sigma_tau_max = ylim_sigma_tau[2]
)

write_csv(
  example_parameters,
  "results/tables/example_02_parameters.csv"
)


# ============================================================
# 12. Plot sigma_3 - sigma_1 cooling path
# ============================================================

plot_sigma3_sigma1 <- ggplot() +
  geom_line(
    data = curve_combined,
    aes(x = sigma_3, y = sigma_1, color = branch),
    linewidth = 1.2
  ) +
  geom_path(
    data = cooling_results_plot,
    aes(x = sigma_3, y = sigma_1),
    linewidth = 1.1,
    color = "black"
  ) +
  geom_point(
    data = cooling_results_plot,
    aes(x = sigma_3, y = sigma_1, color = failure_type),
    size = 2,
    alpha = 0.85
  ) +
  {
    if (nrow(first_failure_point) == 1)
      geom_point(
        data = first_failure_point,
        aes(x = sigma_3, y = sigma_1),
        inherit.aes = FALSE,
        size = 4,
        shape = 21,
        fill = "red",
        color = "black"
      )
  } +
  {
    if (nrow(first_failure_point) == 1)
      geom_text(
        data = first_failure_point,
        aes(
          x = sigma_3,
          y = sigma_1,
          label = paste0("Delta T = ", round(delta_T, 2), " K")
        ),
        inherit.aes = FALSE,
        nudge_y = 0.04 * diff(ylim_sigma3_sigma1),
        size = 4
      )
  } +
  scale_color_manual(
    values = c(
      "NGC" = "blue",
      "UC" = "orange",
      "No failure" = "grey55",
      "Pure extensional fracture" = "red",
      "Transitional / hybrid shear fracture" = "purple"
    )
  ) +
  coord_fixed(
    ratio = 1,
    xlim = xlim_sigma3_sigma1,
    ylim = ylim_sigma3_sigma1,
    expand = FALSE
  ) +
  labs(
    title = "Cooling-induced stress path and NGC–UC failure envelope",
    x = expression(sigma[3]^"'"~"(MPa)"),
    y = expression(sigma[1]^"'"~"(MPa)"),
    color = "Type"
  ) +
  theme_gray(base_size = 14)

print(plot_sigma3_sigma1)

ggsave(
  "results/figures/example_02_cooling_sigma3_sigma1.png",
  plot = plot_sigma3_sigma1,
  width = 8,
  height = 6,
  dpi = 300
)

ggsave(
  "results/figures/example_02_cooling_sigma3_sigma1.pdf",
  plot = plot_sigma3_sigma1,
  width = 8,
  height = 6
)


# ============================================================
# 13. Plot Mohr circles
# ============================================================

plot_mohr <- ggplot() +
  geom_path(
    data = mohr_circles,
    aes(x = sigma_n, y = tau, group = delta_T),
    linewidth = 0.6,
    alpha = 0.65
  ) +
  geom_line(
    data = curve_combined,
    aes(x = sigma_n, y = tau, color = branch),
    linewidth = 1.2
  ) +
  scale_color_manual(
    values = c("NGC" = "blue", "UC" = "orange")
  ) +
  coord_fixed(
    ratio = 1,
    xlim = xlim_sigma_tau,
    ylim = ylim_sigma_tau,
    expand = FALSE
  ) +
  labs(
    title = "Mohr circles during cooling and NGC–UC envelope",
    x = expression(sigma[n]~"(MPa)"),
    y = expression(tau~"(MPa)"),
    color = "Criterion"
  ) +
  theme_gray(base_size = 14)

print(plot_mohr)

ggsave(
  "results/figures/example_02_cooling_mohr_circles.png",
  plot = plot_mohr,
  width = 8,
  height = 6,
  dpi = 300
)

ggsave(
  "results/figures/example_02_cooling_mohr_circles.pdf",
  plot = plot_mohr,
  width = 8,
  height = 6
)


# ============================================================
# 14. Console checks
# ============================================================

cat("\n==============================================\n")
cat("Example 02: Cooling-induced geothermal failure\n")
cat("==============================================\n")
cat("Input curve file :", curve_file, "\n")
cat("Input param file :", param_file, "\n\n")

cat("Physical parameters:\n")
cat("z          =", z, "m\n")
cat("gamma_eff  =", gamma_eff, "kN/m^3\n")
cat("nu         =", nu, "\n")
cat("k0         =", k0, "\n")
cat("alpha_T    =", alpha_T, "1/K\n")
cat("E          =", E, "MPa\n")
cat("T_ini      =", T_ini, "K\n\n")

cat("NGC–UC thresholds:\n")
cat("T0 =", T0, "MPa\n")
cat("C0 =", C0, "MPa\n")
cat("sigma_1_curve_max =", sigma_1_curve_max, "MPa\n")
cat("lambda =", lambda, "\n")
cat("Pure extensional sigma_1 limit =", pure_extensional_sigma1_limit, "MPa\n\n")

cat("Cooling simulation:\n")
cat("Delta T range =", min(delta_T_seq), "to", max(delta_T_seq), "K\n")
cat("Delta T step  =", unique(diff(delta_T_seq))[1], "K\n")

if (nrow(first_failure_point) == 1) {
  cat("First failure at Delta T =", first_failure_point$delta_T, "K\n")
  cat("Failure type:", first_failure_point$failure_type, "\n")
  cat("sigma_1 =", first_failure_point$sigma_1, "MPa\n")
  cat("sigma_3 =", first_failure_point$sigma_3, "MPa\n")
} else {
  cat("No failure detected in the selected cooling range.\n")
}

cat("\nPlot limits:\n")
cat("sigma_3 - sigma_1 xlim:", xlim_sigma3_sigma1, "\n")
cat("sigma_3 - sigma_1 ylim:", ylim_sigma3_sigma1, "\n")
cat("sigma_n - tau xlim:", xlim_sigma_tau, "\n")
cat("sigma_n - tau ylim:", ylim_sigma_tau, "\n")

cat("\nFiles written to:\n")
cat("results/tables/\n")
cat("results/figures/\n")
cat("==============================================\n")