###############################################################
#### Example 03: Thermal failure boundary
#### Delta T required for failure as a function of alpha and E
#### using the combined NGC + Ucar failure criterion
####
#### Purpose:
####   - Read the combined NGC–UC curve generated by script 01
####   - Compute thermo-mechanical stress states at fixed depth
####   - Determine the critical cooling Delta T for each alpha–E pair
####   - Avoid stair-step curves by solving Delta Tcrit with uniroot()
####
#### Required input files:
####   results/tables/curve_combined_NGC_UC.csv
####   results/tables/parameters_NGC_UC.csv
####
#### Outputs:
####   - CSV tables in results/tables/
####   - PNG/PDF figures in results/figures/
####
####
###############################################################

# ============================================================
# 1. Install and load libraries
# ============================================================

paquetes <- c("dplyr", "tidyr", "purrr", "ggplot2", "readr")

instalar_faltantes <- paquetes[
  !sapply(paquetes, requireNamespace, quietly = TRUE)
]

if (length(instalar_faltantes) > 0) {
  install.packages(instalar_faltantes)
}

lapply(paquetes, library, character.only = TRUE)


# ============================================================
# 2. Input files from script 01
# ============================================================

curve_file <- "results/tables/curve_combined_NGC_UC.csv"
param_file <- "results/tables/parameters_NGC_UC.csv"

if (!file.exists(curve_file)) {
  stop("Curve file not found: ", curve_file)
}

if (!file.exists(param_file)) {
  stop("Parameter file not found: ", param_file)
}

curve_combined <- read_csv(curve_file, show_col_types = FALSE)
parameters_ngc_uc <- read_csv(param_file, show_col_types = FALSE)


# ============================================================
# 3. User-defined physical parameters
# ============================================================

z <- 5000              # depth, m
gamma_eff <- 17        # effective unit weight, kN/m^3
nu <- 0.09             # Poisson's ratio

alpha_min <- 15e-6      # 1/K
alpha_max <- 25e-6     # 1/K
n_alpha <- 100

E_vals <- c(60e3, 70e3, 80e3, 90e3, 100e3, 110e3, 120e3)  # MPa

T_ini <- 450            # K, stored for reference

deltaT_min <- 0         # K
deltaT_max <- 250        # K Edit to the desired plot extension

# Numerical tolerance for Delta Tcrit
deltaT_tol <- 0.01      # K


# ============================================================
# 4. Output folders
# ============================================================

dir.create("results", showWarnings = FALSE)
dir.create("results/tables", recursive = TRUE, showWarnings = FALSE)
dir.create("results/figures", recursive = TRUE, showWarnings = FALSE)


# ============================================================
# 5. Basic checks
# ============================================================

stopifnot(z > 0)
stopifnot(gamma_eff > 0)
stopifnot(nu > 0, nu < 0.5)
stopifnot(alpha_min > 0)
stopifnot(alpha_max > alpha_min)
stopifnot(length(E_vals) > 0)
stopifnot(all(E_vals > 0))
stopifnot(deltaT_max > deltaT_min)
stopifnot(deltaT_tol > 0)


# ============================================================
# 6. Extract NGC–UC parameters
# ============================================================

T0 <- parameters_ngc_uc$sigma_t_adj[1]
C0 <- parameters_ngc_uc$sigma_c_adj[1]
lambda <- parameters_ngc_uc$lambda[1]
xi <- T0 / C0

if (!is.finite(T0) || !is.finite(C0) || !is.finite(lambda)) {
  stop("Could not extract T0, C0 or lambda from parameters file.")
}

pure_extensional_sigma1_limit <- -lambda * T0


# ============================================================
# 7. Prepare failure-threshold interpolation
# ============================================================

curve_threshold <- curve_combined %>%
  filter(
    is.finite(sigma_1),
    is.finite(sigma_3),
    sigma_1 >= 0
  ) %>%
  arrange(sigma_1) %>%
  group_by(sigma_1) %>%
  summarise(
    sigma_3_threshold = min(sigma_3, na.rm = TRUE),
    .groups = "drop"
  )

if (nrow(curve_threshold) < 2) {
  stop(
    "Not enough points in the NGC–UC curve to interpolate failure thresholds. ",
    "Consider increasing n_ngc and n_uc in script 01."
  )
}

sigma_1_curve_max <- max(curve_threshold$sigma_1, na.rm = TRUE)

if (sigma_1_curve_max < C0) {
  warning(
    "The available NGC–UC curve does not reach C0 in sigma_1. ",
    "The failure check will be limited to the available curve range: ",
    round(sigma_1_curve_max, 3), " MPa."
  )
}

interp_sigma3_threshold <- approxfun(
  x = curve_threshold$sigma_1,
  y = curve_threshold$sigma_3_threshold,
  rule = 2
)


# ============================================================
# 8. Stress and failure functions
# ============================================================

k0 <- nu / (1 - nu)
sigma_v_ini <- gamma_eff * z / 1000  # MPa

compute_stress <- function(alpha_T, E, deltaT) {
  
  delta_sigma_thermal <- (alpha_T * E / (1 - nu)) * deltaT
  
  sigma_v <- sigma_v_ini - delta_sigma_thermal
  sigma_h <- k0 * sigma_v - delta_sigma_thermal
  
  sigma_1 <- max(sigma_v, sigma_h)
  sigma_3 <- min(sigma_v, sigma_h)
  
  data.frame(
    delta_sigma_thermal = delta_sigma_thermal,
    sigma_v = sigma_v,
    sigma_h = sigma_h,
    sigma_1 = sigma_1,
    sigma_3 = sigma_3
  )
}

check_failure <- function(sigma_1, sigma_3) {
  
  sigma_3_threshold <- interp_sigma3_threshold(sigma_1)
  
  pure_extensional_failure <-
    sigma_3 <= T0 &
    sigma_1 <= pure_extensional_sigma1_limit
  
  hybrid_shear_failure <-
    !pure_extensional_failure &
    sigma_1 <= min(C0, sigma_1_curve_max) &
    sigma_3 <= sigma_3_threshold
  
  failure <- pure_extensional_failure | hybrid_shear_failure
  
  return(failure)
}

classify_failure <- function(sigma_1, sigma_3) {
  
  sigma_3_threshold <- interp_sigma3_threshold(sigma_1)
  
  pure_extensional_failure <-
    sigma_3 <= T0 &
    sigma_1 <= pure_extensional_sigma1_limit
  
  hybrid_shear_failure <-
    !pure_extensional_failure &
    sigma_1 <= min(C0, sigma_1_curve_max) &
    sigma_3 <= sigma_3_threshold
  
  case_when(
    pure_extensional_failure ~ "Pure extensional fracture",
    hybrid_shear_failure ~ "Transitional / hybrid shear fracture",
    TRUE ~ "No failure"
  )
}


# ============================================================
# 9. Find critical Delta T by root finding
# ============================================================

find_deltaTcrit <- function(alpha_T, E) {
  
  stress_min <- compute_stress(alpha_T, E, deltaT_min)
  stress_max <- compute_stress(alpha_T, E, deltaT_max)
  
  failure_min <- check_failure(
    stress_min$sigma_1,
    stress_min$sigma_3
  )
  
  failure_max <- check_failure(
    stress_max$sigma_1,
    stress_max$sigma_3
  )
  
  if (failure_min) {
    return(deltaT_min)
  }
  
  if (!failure_max) {
    return(NA_real_)
  }
  
  objective_function <- function(deltaT) {
    
    stress <- compute_stress(alpha_T, E, deltaT)
    
    sigma_3_threshold <- interp_sigma3_threshold(stress$sigma_1)
    
    pure_margin <- min(
      T0 - stress$sigma_3,
      pure_extensional_sigma1_limit - stress$sigma_1
    )
    
    hybrid_margin <- min(
      min(C0, sigma_1_curve_max) - stress$sigma_1,
      sigma_3_threshold - stress$sigma_3
    )
    
    # Failure occurs when either pure_margin >= 0
    # or hybrid_margin >= 0.
    # The controlling margin is their maximum.
    max(pure_margin, hybrid_margin)
  }
  
  root <- tryCatch(
    uniroot(
      objective_function,
      interval = c(deltaT_min, deltaT_max),
      tol = deltaT_tol
    )$root,
    error = function(e) NA_real_
  )
  
  return(root)
}


# ============================================================
# 10. Compute failure boundary
# ============================================================

alpha_grid <- seq(alpha_min, alpha_max, length.out = n_alpha)

failure_boundary <- expand_grid(
  E = E_vals,
  alpha_T = alpha_grid
) %>%
  mutate(
    deltaT_crit = map2_dbl(alpha_T, E, find_deltaTcrit)
  ) %>%
  mutate(
    E_GPa = E / 1000
  )


# ============================================================
# 11. Compute stress states at critical Delta T
# ============================================================

critical_stress_states <- failure_boundary %>%
  filter(!is.na(deltaT_crit)) %>%
  mutate(
    stress = pmap(
      list(alpha_T, E, deltaT_crit),
      compute_stress
    )
  ) %>%
  unnest(stress) %>%
  mutate(
    sigma_3_threshold = interp_sigma3_threshold(sigma_1),
    failure_type = classify_failure(sigma_1, sigma_3),
    E_GPa = E / 1000
  )


# ============================================================
# 12. Optional diagnostic coarse grid
# ============================================================

# This is only for checking; it is not used to define the smooth boundary.
deltaT_diagnostic_grid <- seq(deltaT_min, deltaT_max, by = 1)

diagnostic_grid <- expand_grid(
  E = E_vals,
  alpha_T = alpha_grid,
  deltaT = deltaT_diagnostic_grid
) %>%
  mutate(
    stress = pmap(
      list(alpha_T, E, deltaT),
      compute_stress
    )
  ) %>%
  unnest(stress) %>%
  mutate(
    sigma_3_threshold = interp_sigma3_threshold(sigma_1),
    failure_type = classify_failure(sigma_1, sigma_3),
    failure = failure_type != "No failure",
    E_GPa = E / 1000
  )


# ============================================================
# 13. Export CSV files
# ============================================================

write_csv(
  failure_boundary,
  "results/tables/example_03_failure_boundary_deltaT_alpha.csv"
)

write_csv(
  critical_stress_states,
  "results/tables/example_03_critical_stress_states.csv"
)

write_csv(
  curve_threshold,
  "results/tables/example_03_sigma3_failure_threshold_from_curve.csv"
)

write_csv(
  diagnostic_grid,
  "results/tables/example_03_diagnostic_grid.csv"
)

example_parameters <- data.frame(
  z = z,
  gamma_eff = gamma_eff,
  nu = nu,
  k0 = k0,
  sigma_v_ini = sigma_v_ini,
  alpha_min = alpha_min,
  alpha_max = alpha_max,
  n_alpha = n_alpha,
  E_vals_MPa = paste(E_vals, collapse = ", "),
  E_vals_GPa = paste(E_vals / 1000, collapse = ", "),
  T_ini = T_ini,
  deltaT_min = deltaT_min,
  deltaT_max = deltaT_max,
  deltaT_tol = deltaT_tol,
  T0 = T0,
  C0 = C0,
  xi = xi,
  sigma_1_curve_max = sigma_1_curve_max,
  lambda = lambda,
  pure_extensional_sigma1_limit = pure_extensional_sigma1_limit
)

write_csv(
  example_parameters,
  "results/tables/example_03_parameters.csv"
)


# ============================================================
# 14. Plot failure boundary
# ============================================================

plot_failure_boundary <- ggplot(
  failure_boundary %>% filter(!is.na(deltaT_crit)),
  aes(
    x = alpha_T,
    y = deltaT_crit,
    color = factor(E_GPa),
    group = E_GPa
  )
) +
  geom_line(linewidth = 1) +
  labs(
    x = expression(alpha[T]~"(K"^{-1}*")"),
    y = expression(Delta*T[crit]~"(K)"),
    color = "E (GPa)",
    title = expression("Failure boundary ("*Delta*T~" vs "*alpha[T]*") for each "~E),
    subtitle = paste0(
      "z = ", z, " m;  k0 = ", round(k0, 3),
      ";  C0 = ", C0, " MPa;  T0 = ", T0,
      " MPa;  xi = ", signif(xi, 4)
    )
  ) +
  theme_gray(base_size = 12)

print(plot_failure_boundary)

ggsave(
  "results/figures/example_03_failure_boundary_deltaT_alpha.png",
  plot = plot_failure_boundary,
  width = 8,
  height = 5,
  dpi = 300
)

ggsave(
  "results/figures/example_03_failure_boundary_deltaT_alpha.pdf",
  plot = plot_failure_boundary,
  width = 8,
  height = 5
)


# ============================================================
# 15. Console checks
# ============================================================

cat("\n==============================================\n")
cat("Example 03: Thermal failure boundary\n")
cat("==============================================\n")
cat("Input curve file :", curve_file, "\n")
cat("Input param file :", param_file, "\n\n")

cat("Physical parameters:\n")
cat("z          =", z, "m\n")
cat("gamma_eff  =", gamma_eff, "kN/m^3\n")
cat("nu         =", nu, "\n")
cat("k0         =", k0, "\n")
cat("sigma_v_ini =", sigma_v_ini, "MPa\n")
cat("alpha range =", alpha_min, "to", alpha_max, "1/K\n")
cat("E values    =", paste(E_vals / 1000, collapse = ", "), "GPa\n\n")

cat("NGC–UC thresholds:\n")
cat("T0 =", T0, "MPa\n")
cat("C0 =", C0, "MPa\n")
cat("xi =", xi, "\n")
cat("sigma_1_curve_max =", sigma_1_curve_max, "MPa\n")
cat("lambda =", lambda, "\n")
cat("Pure extensional sigma_1 limit =", pure_extensional_sigma1_limit, "MPa\n\n")

cat("Boundary calculation:\n")
cat("Delta T max =", deltaT_max, "K\n")
cat("Delta T tolerance =", deltaT_tol, "K\n")
cat("Number of alpha values =", n_alpha, "\n")
cat("Rows in failure boundary table =", nrow(failure_boundary), "\n")
cat("Rows with valid failure =", sum(!is.na(failure_boundary$deltaT_crit)), "\n\n")

cat("Files written to:\n")
cat("results/tables/\n")
cat("results/figures/\n")
cat("==============================================\n")